---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: container
spec:
  build:
    builderRef:
      name: brew-v1
    params:
      type: container
      source-ref: cpaas-tp-1.7-rhel-7
      source-repo: containers/cpaas-test-brew-container
      target: cpaas-tp-1.7-rhel-7-containers-candidate
