
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: DOCKERFILE
    type: string
  results:
  - name: IMAGE_URL
    value: $(tasks.build-push.results.IMAGE_URL)
  - name: IMAGE_DIGEST
    value: $(tasks.build-push.results.IMAGE_DIGEST)
  workspaces:
  - name: shared-data
  - name: docker-credentials
  tasks:
  - name: fetch-source
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/joejstuart/hacbs-docker-build.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/git-clone.yaml
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-push
    runAfter: ["fetch-source"]
    taskRef:
      name: buildah
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
